### PR TITLE
Drop support for Python 2 and remove version pinning

### PR DESCRIPTION
**Pull request by viktordick**

### CODE REVIEW

**Comment by viktordick** [comment]
Addresses #9 - we could actually only remove the version pinning and not also drop Python 2 support in the same step.
This still needs to be tested on a system that actually uses an ODBC connection. I only tested that this installs in Python 3.11 and the zodbsync test is successful, but that only creates a connector and does not actually use it.

**Review by jan-jockusch — APPROVED** [review]
LGTM

**Comment by viktordick** [comment]
@jan-jockusch This will probably become relevant for next week if we want to change our template system to Debian. I just changed my laptop to Debian this week and could not install `perfact-dbutils-zope4` because of this.

Before merging this, we need to test that it actually works, on a system which actually uses ODBC connections.

**Comment by viktordick** [comment]
Tested locally with an odbc connection onto my own perfactema database

**Pull request merged**
